//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GIV.Interlis2.Tools.App.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GIV.Interlis2.Tools.App.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vorgang wurde vom Benutzender abgebrochen..
        /// </summary>
        public static string AbortFromUser {
            get {
                return ResourceManager.GetString("AbortFromUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GIV - Interlis2 Tool.
        /// </summary>
        public static string AppTitle {
            get {
                return ResourceManager.GetString("AppTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Konvertieren.
        /// </summary>
        public static string ButtonConvert {
            get {
                return ResourceManager.GetString("ButtonConvert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Öffnen.
        /// </summary>
        public static string ButtonOpen {
            get {
                return ResourceManager.GetString("ButtonOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wählen.
        /// </summary>
        public static string ButtonSelect {
            get {
                return ResourceManager.GetString("ButtonSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Funktion [{0}] mit Meldungen beendet....
        /// </summary>
        public static string EndCommandErrorMessage {
            get {
                return ResourceManager.GetString("EndCommandErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Funktion [{0}] beendet....
        /// </summary>
        public static string EndCommandSuccessMessage {
            get {
                return ResourceManager.GetString("EndCommandSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ausführung ist ein Problem aufgetretten: [{0}]..
        /// </summary>
        public static string GeneralRuntimeMessage {
            get {
                return ResourceManager.GetString("GeneralRuntimeMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Info - Logger.
        /// </summary>
        public static string LabelInfoLogger {
            get {
                return ResourceManager.GetString("LabelInfoLogger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quell-Datei:.
        /// </summary>
        public static string LabelInputFile {
            get {
                return ResourceManager.GetString("LabelInputFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Protokoll-Datei:.
        /// </summary>
        public static string LabelLogFile {
            get {
                return ResourceManager.GetString("LabelLogFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ziel-Datei:.
        /// </summary>
        public static string LabelOutputFile {
            get {
                return ResourceManager.GetString("LabelOutputFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Protkoll-Datei erstellt:.
        /// </summary>
        public static string LogFileMessage {
            get {
                return ResourceManager.GetString("LogFileMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vorhande Dateien überschreiben....
        /// </summary>
        public static string MessageBoxFileFoundWillOverwrite {
            get {
                return ResourceManager.GetString("MessageBoxFileFoundWillOverwrite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DSS in TG-GEP.
        /// </summary>
        public static string RadioButtonDssToTggep {
            get {
                return ResourceManager.GetString("RadioButtonDssToTggep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DSS in TG-MEL.
        /// </summary>
        public static string RadioButtonDssToTgmel {
            get {
                return ResourceManager.GetString("RadioButtonDssToTgmel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter DSS in TG-MEL.
        /// </summary>
        public static string RadioButtonTgmelFilter {
            get {
                return ResourceManager.GetString("RadioButtonTgmelFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Funktion [{0}] wird gestartet....
        /// </summary>
        public static string StartCommandMessage {
            get {
                return ResourceManager.GetString("StartCommandMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Der angegebene Typ [{0}] wurde nicht gefunden..
        /// </summary>
        public static string TypeNotFoundErrorMessage {
            get {
                return ResourceManager.GetString("TypeNotFoundErrorMessage", resourceCulture);
            }
        }
    }
}
