//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GIV.Interlis2.Tools.ConsoleApp.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GIV.Interlis2.Tools.ConsoleApp.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Die Eingaben sind ungenügend um einen Befehl korrekt ausführen zu können..
        /// </summary>
        internal static string MainConsoleCantNotStartConvertErrorMessage {
            get {
                return ResourceManager.GetString("MainConsoleCantNotStartConvertErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Funktion [{0}] mit Meldungen beendet....
        /// </summary>
        internal static string MainConsoleEndCommandErrorMessage {
            get {
                return ResourceManager.GetString("MainConsoleEndCommandErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Funktion [{0}] beendet....
        /// </summary>
        internal static string MainConsoleEndCommandSuccessMessage {
            get {
                return ResourceManager.GetString("MainConsoleEndCommandSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datei wurde nicht gefunden [{0}]..
        /// </summary>
        internal static string MainConsoleFileNotFoundErrorMessage {
            get {
                return ResourceManager.GetString("MainConsoleFileNotFoundErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bei der Ausführung ist ein Problem aufgetretten: [{0}]..
        /// </summary>
        internal static string MainConsoleGeneralRuntimeMessage {
            get {
                return ResourceManager.GetString("MainConsoleGeneralRuntimeMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log-Datei erstellt:.
        /// </summary>
        internal static string MainConsoleLogFileMessage {
            get {
                return ResourceManager.GetString("MainConsoleLogFileMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ein benotigtes Argument [{0}] wurde nicht angegeben..
        /// </summary>
        internal static string MainConsoleMissingArgumentErrorMessage {
            get {
                return ResourceManager.GetString("MainConsoleMissingArgumentErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drücke eine belibige Taste für das Beenden der Konsole.
        /// </summary>
        internal static string MainConsolePressAnyKeyForExit {
            get {
                return ResourceManager.GetString("MainConsolePressAnyKeyForExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Funktion [{0}] wird gestartet....
        /// </summary>
        internal static string MainConsoleStartCommandMessage {
            get {
                return ResourceManager.GetString("MainConsoleStartCommandMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GIV-TG - Interlis2 Tool.
        /// </summary>
        internal static string MainConsoleTitle {
            get {
                return ResourceManager.GetString("MainConsoleTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Der angegebene Typ [{0}] wurde nicht gefunden..
        /// </summary>
        internal static string MainConsoleTypeNotFoundErrorMessage {
            get {
                return ResourceManager.GetString("MainConsoleTypeNotFoundErrorMessage", resourceCulture);
            }
        }
    }
}
